### ISSUE TITLE
export options for batch conversion

### ISSUE THREAD

**Issue by cwittern** [nhoffman/org-export#11]
Hi there,
first of all, this is a great tool, thank you for making it available!  This helps a lot.
Now, I would like to have specific options activated when doing batch export, which are different from what I need with interactive export.  Would it be feasible to provide them somewhere, maybe as a config file or sth similar?
Cheers,
Chris

**Comment by nhoffman** [comment]
Hi @cwittern - sorry for the long delay - I haven't been working on this lately. Do you mean that you would like to invoke specific org-mode options? Can you provide an example of what you are trying to do?

**Comment by nhoffman** [comment]
@cwittern - just leaving a note here as I close this. I recently added options to provide additional configuration in the form of elisp expressions on the command line or in files - maybe this will address this issue. Feel free to reopen with more explanation if you still have any interest in this!
