### ISSUE TITLE
How does this compare to org_reader?

### ISSUE THREAD

**Issue by Thaodan** [nhoffman/org-export#12]
How does compare to org_reader from pelican plugins?

**Comment by nhoffman** [comment]
@Thaodan - sorry for the long delayed response - returning to this project after not thinking about it for a while. I'm not familiar with that project (thanks for pointing it out!), but if this is what you are referring to (https://github.com/getpelican/pelican-plugins/blob/master/org_python_reader/README.org), I'd say that the most obvious difference is that this project uses emacs to render org-mode files, and that one uses the "orgco" python package. 

Closing this issue but feel free to reopen!
