### ISSUE TITLE
org-export incorrectly complains about Emacs version

### ISSUE THREAD

**Issue by bharris-fs** [nhoffman/org-export#8]
I'm running Emacs 25.3 on W7; I cloned org-export a few minutes ago.

I first set EMACS as suggested:
`
me@mymachine ~/sandboxorg
$ export EMACS=/cygdrive/c/emacs/emacs-25.3/bin/runemacs.exe
`
Then I tried it out:
`
me@mymachine ~/sandboxorg
$ ./org-export/org-export pdf --infile batchtest.org
Using /cygdrive/c/emacs/emacs-25.3/bin/runemacs.exe,
Error: Emacs version 24.2+ is required
`
I then ran `emacs -- version`:
`me@mymachine ~/sandboxorg
$ /cygdrive/c/emacs/emacs-25.3/bin/runemacs.exe --version`

That is, I simply get a blank line.

If I drop the `--version`, I get a new Emacs instance, so it is pointing to the correct place.  If I run `M-x version` inside that Emacs, I get `GNU Emacs 25.3.1 (x86_64-w64-mingw32) of 2017-09-12`.

Any suggestions as to what I'm missing?

Incidentally, this problem arose using Vincent Goulet's Emacs installation on W7.  Trying it on Debian Stable was successful.

**Comment by nhoffman** [comment]
Sorry for the extremely belated response. I'm dropping support for emacs versions below 26, so I suspect this issue is now moot. I don't really have the ability to test on wondows, but if you ever want to give it another shot, let me know how it goes.
