### ISSUE TITLE
org-export modifies system?

### ISSUE THREAD

**Issue by bharris-fs** [nhoffman/org-export#9]
In reading the description of org-export a second time and in skimming org-export-cli.el, I'm a bit worried about org-export's desire to update my system.  In a way, that's good; you seem to be trying to ensure org-export users have a consistent and up-to-date environment.  MiKTeX does that for LaTeX packages, for example.

Still, I've sometimes had troubles after upgrading elpa packages including org-mode, and so I'd much rather do that myself.  Can you add a command line option that either runs using the system as it finds it or reports back on stderr what system config problems it detected?  

Because options are easy to forget, I'd suggest the default state be _not_ to change anything on the local system, making the user set an option to get automatic updates.  

Alternatively and perhaps better, make org-export do no updating and, if you wish, create  org-export-updater that does nothing but detect and report any problems and optionally (default off) updates  a system.

Or did I misunderstand how org-export works?

**Comment by nhoffman** [comment]
Hi @bharris-fs - sorry for the long delay, I haven't been working on this lately. Let me clarify what you mean by "updating the system": ``org-export`` stores its own version of packages in ``~/.org-export``, precisely to avoid modifying the user's ``~/.emacs.d``. The intended behavior is that after the dependencies are installed on first run, an update can be triggered using ``org-export cli --package-upgrade``, but nothing is updated by default. I think that this is the behavior that you are recommending. Are you experiencing something different?

**Comment by nhoffman** [comment]
Update: dependencies are now saved in ``$XDG_DATA_HOME/org-export``, although the substance of the comment above is still correct. Please reopen if necessary.
